#!/bin/bash

sbatch restManagerSimToAnaTrackCo60CapacitorBottom_halfway.sh
sbatch restManagerSimToAnaTrackCo60CapacitorTop_halfway.sh
sbatch restManagerSimToAnaTrackCo60ResistanceTop_halfway.sh

sbatch restManagerSimToAnaTrackCs137CapacitorBottom_halfway.sh
sbatch restManagerSimToAnaTrackCs137CapacitorTop_halfway.sh
sbatch restManagerSimToAnaTrackCs137ResistanceTop_halfway.sh

sbatch restManagerSimToAnaTrackK40CapacitorBottom_halfway.sh
sbatch restManagerSimToAnaTrackK40CapacitorTop_halfway.sh
sbatch restManagerSimToAnaTrackK40ResistanceTop_halfway.sh

sbatch restManagerSimToAnaTrackTh228CapacitorBottom_halfway.sh
sbatch restManagerSimToAnaTrackTh228CapacitorTop_halfway.sh
sbatch restManagerSimToAnaTrackTh228ResistanceTop_halfway.sh

sbatch restManagerSimToAnaTrackRa226CapacitorBottom_halfway.sh
sbatch restManagerSimToAnaTrackRa226CapacitorTop_halfway.sh