#!bin/bash

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/TrackAnalysis

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra228_Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_CapTopCentre

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra228_Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_CapTopCentre/TrackAnalysis

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra228_Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137_CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40_CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228_ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238_CapTopCentre/TrackAnalysis/Plots