#!bin/bash

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/TrackAnalysis

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra228Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238CapTopCentre

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra228Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238CapTopCentre/TrackAnalysis

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra228Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Co60ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th232ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Cs137CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/K40CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Ra226ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/Th228ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_halfway/U238CapTopCentre/TrackAnalysis/Plots