#!bin/bash

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/TrackAnalysis

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra228Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228Chip
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238CapBottomCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40CapTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228ResTopCentre
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238CapTopCentre

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra228Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228Chip/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238CapBottomCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40CapTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228ResTopCentre/TrackAnalysis
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238CapTopCentre/TrackAnalysis

mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra228Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Co60ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th232ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228Chip/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238CapBottomCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Cs137CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/K40CapTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Ra226ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/Th228ResTopCentre/TrackAnalysis/Plots
mkdir ~/RPE_IAXO_REST_v2.2.10/data/IAXOD0/Argon_AGET_closer/U238CapTopCentre/TrackAnalysis/Plots