#!bin/bash

sbatch restG4U238FromChip_halfway.sh
sbatch restG4Ra226FromChip_halfway.sh
sbatch restG4Ra228FromChip_halfway.sh
sbatch restG4Th228FromChip_halfway.sh
sbatch restG4K40FromChip_halfway.sh

sbatch restG4U238FromChip_halfway.sh
sbatch restG4Ra226FromChip_halfway.sh
sbatch restG4Ra228FromChip_halfway.sh
sbatch restG4Th228FromChip_halfway.sh
sbatch restG4K40FromChip_halfway.sh