#!bin/bash
export ENERGY_keV="1."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="1.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="2.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="3.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="4.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="5.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="6.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="7.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="8.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.1"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.2"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.3"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.4"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.5"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.6"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.7"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.8"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="9.9"
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
export ENERGY_keV="10."
restG4 ${HOME}/RPE_IAXO_REST_v2.2.10/IAXO_AGET-REST/G4sims/restSims/AGET/Electronics_halfway/XraysFromPipe.rml
