#!bin/bash

sbatch restG4U238FromChip_outside.sh
sbatch restG4Ra226FromChip_outside.sh
sbatch restG4Ra228FromChip_outside.sh
sbatch restG4Th228FromChip_outside.sh
sbatch restG4K40FromChip_outside.sh

sbatch restG4U238FromChip_outside.sh
sbatch restG4Ra226FromChip_outside.sh
sbatch restG4Ra228FromChip_outside.sh
sbatch restG4Th228FromChip_outside.sh
sbatch restG4K40FromChip_outside.sh